<a href="https://colab.research.google.com/github/shadmanshakib09/Machine-Learning-and-Deep-Learning/blob/main/Sentiment_Analysis_using_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***INTEGER ENCODING***

In [13]:
import numpy as np

docs = ['hi',
        'how are you',
        'how is your day going',
        'I am fine',
        'are you free tomorrow']

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')
tokenizer.fit_on_texts(docs)


**oov_token = Keras lets us define an Out Of Vocab token - this will replace any unknown words with a token of our choosing.**



In [15]:
tokenizer.word_index

{'<nothing>': 1,
 'how': 2,
 'are': 3,
 'you': 4,
 'hi': 5,
 'is': 6,
 'your': 7,
 'day': 8,
 'going': 9,
 'i': 10,
 'am': 11,
 'fine': 12,
 'free': 13,
 'tomorrow': 14}

In [16]:
tokenizer.word_counts

OrderedDict([('hi', 1),
             ('how', 2),
             ('are', 2),
             ('you', 2),
             ('is', 1),
             ('your', 1),
             ('day', 1),
             ('going', 1),
             ('i', 1),
             ('am', 1),
             ('fine', 1),
             ('free', 1),
             ('tomorrow', 1)])

In [17]:
len(tokenizer.word_index)

14

In [18]:
tokenizer.document_count

5

In [19]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[5], [2, 3, 4], [2, 6, 7, 8, 9], [10, 11, 12], [3, 4, 13, 14]]

In [20]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 5,  0,  0,  0,  0],
       [ 2,  3,  4,  0,  0],
       [ 2,  6,  7,  8,  9],
       [10, 11, 12,  0,  0],
       [ 3,  4, 13, 14,  0]], dtype=int32)

# ***EMBEDDING LAYER INTRODUCED***

In [25]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [29]:
model_2 = Sequential()
model_2.add(Embedding(14, output_dim=2, input_length=5, input_shape=(5,)))
model_2.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ (None, 5, 2)                │              28 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 28 (112.00 B)

 Trainable params: 28 (112.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model_2.compile('adam', 'accuracy')

In [31]:
pred = model_2.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
[[[ 0.03649471  0.04277862]
  [-0.01020976 -0.00956867]
  [-0.01020976 -0.00956867]
  [-0.01020976 -0.00956867]
  [-0.01020976 -0.00956867]]

 [[-0.0057937  -0.02199161]
  [-0.03819598 -0.02260016]
  [ 0.02464728 -0.04684848]
  [-0.01020976 -0.00956867]
  [-0.01020976 -0.00956867]]

 [[-0.0057937  -0.02199161]
  [-0.04118209  0.03884517]
  [-0.00331553  0.04249734]
  [-0.03722757  0.04739388]
  [ 0.00220711 -0.01890482]]

 [[ 0.0019433  -0.00587225]
  [ 0.00288787  0.00283492]
  [-0.04476298  0.0154902 ]
  [-0.01020976 -0.00956867]
  [-0.01020976 -0.00956867]]

 [[-0.03819598 -0.02260016]
  [ 0.02464728 -0.04684848]
  [ 0.0047243   0.00803339]
  [ 0.0047243   0.00803339]
  [-0.01020976 -0.00956867]]]


# ***INTEGER ENCODING USING DATASET***

In [33]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [34]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [35]:
X_train.shape

(25000,)

In [36]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [37]:
#X_train[0]
len(X_train[0])


218

In [38]:
len(X_train[1])

189

In [39]:
X_train = pad_sequences(X_train, padding='post')
X_test = pad_sequences(X_test, padding='post')

In [40]:
X_train.shape

(25000, 2494)

In [41]:
X_train

array([[   1,   14,   22, ...,    0,    0,    0],
       [   1,  194, 1153, ...,    0,    0,    0],
       [   1,   14,   47, ...,    0,    0,    0],
       ...,
       [   1,   11,    6, ...,    0,    0,    0],
       [   1, 1446, 7079, ...,    0,    0,    0],
       [   1,   17,    6, ...,    0,    0,    0]], dtype=int32)

# ***FOR INTEGER ENCODING***

In [10]:
model = Sequential()
model.add(SimpleRNN(32, input_shape=(2494, 1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 233s 295ms/step - accuracy: 0.4991 - loss: 0.6949 - val_accuracy: 0.5069 - val_loss: 0.6932
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 259s 293ms/step - accuracy: 0.4977 - loss: 0.6949 - val_accuracy: 0.4995 - val_loss: 0.6934
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 261s 292ms/step - accuracy: 0.4993 - loss: 0.6938 - val_accuracy: 0.5005 - val_loss: 0.6932
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 262s 291ms/step - accuracy: 0.5033 - loss: 0.6937 - val_accuracy: 0.4969 - val_loss: 0.6947
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 262s 291ms/step - accuracy: 0.5040 - loss: 0.6940 - val_accuracy: 0.5031 - val_loss: 0.6934


# ***FOR EMBEDDINGS***

In [43]:
model_3 = Sequential()
model_3.add(Embedding(10000, 2,input_shape=(2494,)))
model_3.add(SimpleRNN(32,  return_sequences=False))
model_3.add(Dense(1, activation='sigmoid'))
model_3.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ (None, 2494, 2)             │          20,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model_3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_3.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 221s 279ms/step - accuracy: 0.5056 - loss: 0.6971 - val_accuracy: 0.5068 - val_loss: 0.6931
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 260s 278ms/step - accuracy: 0.4975 - loss: 0.6937 - val_accuracy: 0.5028 - val_loss: 0.6938
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 262s 278ms/step - accuracy: 0.4995 - loss: 0.6954 - val_accuracy: 0.5000 - val_loss: 0.6946
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 262s 278ms/step - accuracy: 0.4996 - loss: 0.6953 - val_accuracy: 0.5000 - val_loss: 0.6939
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 262s 278ms/step - accuracy: 0.5005 - loss: 0.6938 - val_accuracy: 0.5001 - val_loss: 0.6932
